# Generated by Django 4.2.5 on 2023-10-02 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='YoutubeTranscription',
            fields=[
                ('YoutubeId', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('YoutubeURL', models.CharField(max_length=50, null=True)),
                ('dateRetrived', models.DateTimeField(auto_now=True)),
                ('cached', models.BooleanField()),
                ('Transcript', models.CharField(max_length=20000)),
            ],
        ),
    ]
