# Generated by Django 4.2.5 on 2023-10-13 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YoutubeApp', '0001_CreateYoutubeTranscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubetranscription',
            name='Summary',
            field=models.CharField(default='none', max_length=20000),
            preserve_default=False,
        ),
    ]
