# Generated by Django 4.2.5 on 2023-10-13 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YoutubeApp', '0002_AddedFieldToYoutubeTrascription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtubetranscription',
            name='Transcript',
            field=models.TextField(),
        ),
    ]
