# Generated by Django 4.2.5 on 2023-10-13 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YoutubeApp', '0004_ChangedFieldTypeAgain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtubetranscription',
            name='YoutubeId',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
