# Generated by Django 4.2.5 on 2023-11-02 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YoutubeApp', '0007_AddedIdsToBeUnique'),
    ]

    operations = [
        migrations.AddField(
            model_name='userwatching',
            name='Title',
            field=models.CharField(default='null'),
            preserve_default=False,
        ),
    ]
