# Generated by Django 4.2.5 on 2023-11-09 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YoutubeApp', '0008_AddTitleField'),
    ]

    operations = [
        migrations.AddField(
            model_name='userwatching',
            name='dateRetrived',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
