# Generated by Django 4.2.5 on 2023-11-09 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YoutubeApp', '0009_adddateRetrived'),
    ]

    operations = [
        migrations.AddField(
            model_name='userwatching',
            name='PosterURL',
            field=models.CharField(default='https://fastly.picsum.photos/id/435/200/300.jpg?hmac=gSfIK7r5rB4f3aJq0RTylep967d4sBRbIUuAOuq433o'),
            preserve_default=False,
        ),
    ]
