# Generated by Django 4.2.5 on 2023-11-10 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YoutubeApp', '0010_addURL'),
    ]

    operations = [
        migrations.AddField(
            model_name='userwatching',
            name='state',
            field=models.CharField(choices=[('W', 'Watched'), ('NS', 'Not Started'), ('IP', 'In Progress')], default='NS', max_length=2),
        ),
    ]
