# Generated by Django 4.2.5 on 2024-03-08 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YoutubeApp', '0011_AddState'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtubetranscription',
            name='YoutubeURL',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
